version: '3'
services:
  app:
    restart: always
    build:
      context: ./.docker/php
    volumes:
      - ./:/var/www/
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - db
    networks:
      - application-network

  nginx:
    build: ./.docker/nginx
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./:/var/www
    depends_on:
      - app
    networks:
      - application-network

  db:
    image: mysql:8.0.25
    platform: linux/x86_64
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: qop
      MYSQL_ROOT_PASSWORD: qop
      MYSQL_PASSWORD: qop
      MYSQL_USER: qop
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - application-network
    depends_on:
      - db-test

  db-test:
    image: mysql:8.0.25
    platform: linux/x86_64
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '33061:3306'
    environment:
      MYSQL_DATABASE: qop
      MYSQL_ROOT_PASSWORD: qop
      MYSQL_PASSWORD: qop
      MYSQL_USER: qop
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql-test:/docker-entrypoint-initdb.d
    networks:
      - application-network

networks:
  application-network:
    driver: bridge